module:
  backup_migrate: 0
  basic_auth: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  config_inspector: 0
  contextual: 0
  datetime: 0
  dblog: 0
  editor: 0
  entity_reference: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  hal: 0
  image: 0
  link: 0
  ncd8_config_manager: 0
  ncd8_config_rest: 0
  node: 0
  options: 0
  path: 0
  quickedit: 0
  rest: 0
  restui: 0
  serialization: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  views: 0
  views_ui: 0
  minimal: 1000
theme:
  stark: 0
  classy: 0
  bartik: 0
  seven: 0
